language: java

before_install:

#install:
#- echo ">>>>>>>>>install"

before_script:

script:

after_success:

after_failure:

after_script:

branchs:
  only:
  - master 
  
notifications:
  email:
    recipients:
    - sypeng@ifytek.com
    on_success: always
    on_failure: always
    
addons:
