language: java

before_install:
- echo ">>>>>>>>>before_install"

install:
- echo ">>>>>>>>>install"

before_script:
- echo ">>>>>>>>>before_script"

script:
- echo ">>>>>>>>>script"

after_success:
- echo ">>>>>>>>>after_success"

after_failure:
- echo ">>>>>>>>>after_failure"

after_script:
- echo ">>>>>>>>>after_script"

branchs:
  only:
  - master 
  
notifications:
  email:
    recipients:
    - sypeng@ifytek.com
    on_success: always
    on_failure: always
    
addons:
